name: Setup Server Environment

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: [self-hosted, ubuntu-20.04]

    steps:
    - name: Update apt
      run: sudo apt update -y

    - name: Install Apache2
      run: sudo apt install -y apache2

    - name: Install PHP and Extensions
      run: |
        sudo apt install -y php7.4 php7.4-{cli,common,bcmath,zip,mysql,xml,curl}
        
    - name: Install MySQL Server
      run: sudo apt install -y mysql-server

    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php
        php composer.phar
        sudo mv composer.phar /usr/local/bin/composer

    - name: Install Git
      run: sudo apt install -y git

    - name: Install Unzip
      run: sudo apt install -y unzip
