name: Copy Ahmad.txt File

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Clone Project 
      run: git clone https://github.com/ahmad474s/g_action_ahmad.txt.git /home/ahmad/my_scripts
