name: Setup Server Environment

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: self-hosted

    steps:
    - name: Update apt
      run: sudo apt update -y

    - name: Install Apache2
      run: sudo apt install -y apache2

    - name: Install PHP and Extensions
      run: |
        sudo apt install -y php7.4 php7.4-{cli,common,bcmath,zip,mysql,xml,curl}
        
    - name: Install MySQL Server
      run: sudo apt install -y mysql-server

    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php
        php composer.phar
        sudo mv composer.phar /usr/local/bin/composer

    - name: Install Git
      run: sudo apt install -y git

    - name: Install Unzip
      run: sudo apt install -y unzip
    - name: Install MySQL Server
      run: sudo apt install -y mysql-server

    - name: Start MySQL Service
      run: sudo service mysql start

    - name: Set up MySQL
      uses: appleboy/setup-mysql@v2
      with:
        mysql-version: '5.7'
        root-password: ${{ secrets.MYSQL_ROOT_PASSWORD }}

    - name: Update User Password and Flush Privileges
      run: |
        echo "ALTER USER 'farhan'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '9089';" | mysql -u root -p"${{ secrets.MYSQL_ROOT_PASSWORD }}"
        echo "FLUSH PRIVILEGES;" | mysql -u root -p"${{ secrets.MYSQL_ROOT_PASSWORD }}"

    - name: Display MySQL Version
      run: mysql --version
