name: Copy Ahmad.txt File

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Clone Project 
      run: |
            sudo apt get update
            sudo apt install php

