name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create File
        run: echo "my name is Ahmad" > ahmad.txt

      - name: Copy File to Local Machine
        uses: appleboy/scp-action@v0.3.0
        with:
          host: ${{ secrets.H_NAME_I }}
          username: ${{ secrets.H_NAME }}
          key: ${{ secrets.G_ACTION_PUBKEY }}
          source: ahmad.txt
          target: /home/ahmad/Test_action_github
