name: Install Dependencies

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update apt
      run: sudo apt update -y

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # Choose your PHP version

    - name: Display PHP Version
      run: php --version

    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php -r "if (hash_file('sha384', 'composer-setup.php') === 'YOUR_SHA384_HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
        php composer-setup.php --install-dir=/usr/local/bin --filename=composer
        php -r "unlink('composer-setup.php');"

    - name: Display Composer Version
      run: composer --version
