name: Install Dependencies

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update apt
      run: sudo apt update -y

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # Choose your PHP version

    - name: Display PHP Version
      run: php --version

    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php
        php composer.phar
        sudo mv composer.phar /usr/local/bin/composer

    - name: Display Composer Version
      run: composer --version
